name: Docker Image Build and Push

on: push

jobs:
  push_to_docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: List files in build context
        run: ls -lR
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ivanovn7/library-management-system:latest
          context: .  # Ensure this is correct based on your repository structure
